name: Build & Test

#Configurar el entorno con JDK adecuado.
#Compilar el código con Maven o Gradle.
#Ejecutar pruebas unitarias con JUnit.
#Generar informes de cobertura de código.

on:
  push:
    branches:
      - main
      - develop
      - function
  pull_request:
    branches:
      - main
      - develop
      - function

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Tests
        run: mvn test
